import 'package:flutter/foundation.dart';

class CsDirectory {
  final user_id,
      practice_number,
      NAME,
      QUALIFICATION,
      ADDR1,
      ADDR2,
      ADDR3,
      POSTCODE,
      TEL,
      FAX,
      EMAIL,
      COMPANY,
      branch,
      NO_CREDITS,
      NOTES,
      PRACTICE,
      sector,
      CPSK,
      biography,
      gender,
      membership_no,
      practice_sector,
      photo,
      PHYSICAL;

  CsDirectory({
    @required this.user_id,
    @required this.practice_number,
    @required this.NAME,
    @required this.QUALIFICATION,
    @required this.ADDR1,
    @required this.ADDR2,
    @required this.ADDR3,
    @required this.POSTCODE,
    @required this.TEL,
    @required this.FAX,
    @required this.EMAIL,
    @required this.COMPANY,
    @required this.branch,
    @required this.NO_CREDITS,
    @required this.NOTES,
    @required this.PRACTICE,
    @required this.sector,
    @required this.CPSK,
    @required this.biography,
    @required this.gender,
    @required this.photo,
    @required this.membership_no,
    @required this.practice_sector,
    @required this.PHYSICAL,
  });

  static CsDirectory fromJson(dynamic json) {
    return CsDirectory(
      user_id: json['user_id'],
      practice_number: json['practice_number'],
      NAME: json['NAME'],
      QUALIFICATION: json['QUALIFICATION'],
      ADDR1: json['ADDR1'],
      ADDR2: json['ADDR2'],
      ADDR3: json['ADDR3'],
      POSTCODE: json['POSTCODE'],
      TEL: json['TEL'],
      FAX: json['FAX'],
      EMAIL: json['EMAIL'],
      COMPANY: json['COMPANY'],
      branch: json['branch'],
      NO_CREDITS: json['NO_CREDITS'],
      NOTES: json['NOTES'],
      PRACTICE: json['PRACTICE'],
      sector: json['sector'],
      CPSK: json['CPSK'],
      biography: json['biography'],
      gender: json['gender'],
      photo: json['photo'],
      membership_no: json['membership_no'],
      practice_sector: json['practice_sector'],
      PHYSICAL: json['PHYSICAL'],
    );
  }
}
